### PR TITLE
config for alacritty

### PR DESCRIPTION
**Pull request by bhanurapelly**
This is a config file for alacritty with material ocean theme enabled along with "Source Code Pro" as the font.

### CODE REVIEW

**Comment by Blacksuan19** [comment]
Nice work!
Could you make a separate repo for it with a screenshot and install instructions like this one https://github.com/material-ocean/Termite-theme

This main repo is only for listing applications and main Xresources file

**Comment by bhanurapelly** [comment]
Yay! Finally completed the task. Please check the repo for updates.

**Comment by Blacksuan19** [comment]
Should be a separate repo not a fork of this

**Comment by bhanurapelly** [comment]
The link points to a seperate repo. https://github.com/TezRyuga/Alacritty-MaterialOcean
Did I do it right this time?
Thanks for the response.

**Comment by Blacksuan19** [comment]
created separate repo for alacritty theme

**Pull request closed without merging**
